#kitpages_edm_add_directory:
#    pattern:  /addDirectory/{parentNodeId}
#    defaults: { _controller: KitpagesEdmBundle:Node:addDirectory }
#    requirements:
#        parentNodeId: \d+


kitpages_edm_render:
    pattern:  /render
    defaults: { _controller: KitpagesEdmBundle:Node:renderFile }

kitpages_edm_add_directory:
    pattern:  /addDirectory
    defaults: { _controller: KitpagesEdmBundle:Node:addDirectory }

kitpages_edm_edit_directory:
    pattern:  /editDirectory/{nodeId}
    defaults: { _controller: KitpagesEdmBundle:Node:editDirectory }
    requirements:
        nodeId: \d+

kitpages_edm_add_file:
    pattern:  /addFile
    defaults: { _controller: KitpagesEdmBundle:Node:addFile }

kitpages_edm_add_file_version:
    pattern:  /addFileVersion
    defaults: { _controller: KitpagesEdmBundle:Node:addFileVersion }

kitpages_edm_view_node:
    pattern:  /node/{nodeId}
    defaults: { _controller: KitpagesEdmBundle:Node:view }
    requirements:
        nodeId: \d+

kitpages_edm_delete_old_file_version:
    pattern:  /deleteOldFileVersionFile/{nodeId}
    defaults: { _controller: KitpagesEdmBundle:Node:deleteOldFileVersion }
    requirements:
        nodeId: \d+

kitpages_edm_disable_node:
    pattern:  /disableNode/{nodeId}
    defaults: { _controller: KitpagesEdmBundle:Node:disableNode }
    requirements:
        nodeId: \d+

kitpages_edm_retrieve_node:
    pattern:  /retrieveNode/{nodeId}
    defaults: { _controller: KitpagesEdmBundle:Node:retrieveNode }
    requirements:
        nodeId: \d+

kitpages_edm_delete_node:
    pattern:  /deleteNode/{nodeId}
    defaults: { _controller: KitpagesEdmBundle:Node:deleteNode }
    requirements:
        nodeId: \d+

kitpages_edm_move_up_node:
    pattern:  /moveUpNode/{nodeId}
    defaults: { _controller: KitpagesEdmBundle:Node:moveUp }
    requirements:
        nodeId: \d+

kitpages_edm_move_down_node:
    pattern:  /moveDownNode/{nodeId}
    defaults: { _controller: KitpagesEdmBundle:Node:moveDown }
    requirements:
        nodeId: \d+

kitpages_edm_export_node:
    pattern:  /export/{nodeId}
    defaults: { _controller: KitpagesEdmBundle:Node:export }
    requirements:
        nodeId: \d+

kitpages_edm_userpreference_tree:
    pattern:  /userPreference/tree
    defaults: { _controller: KitpagesEdmBundle:Tree:saveUserPreferenceTree }

kitpages_edm_userpreference_tree_scroll:
    pattern:  /userPreference/treeScroll
    defaults: { _controller: KitpagesEdmBundle:Tree:saveUserPreferenceTreeScroll }

kitpages_edm_upload_status:
    pattern:  /uploadStatus/{uploadProgressName}
    defaults: { _controller: KitpagesEdmBundle:Node:uploadStatus }
