<?php

namespace Kitpages\EdmBundle\Repository;

use Gedmo\Tree\Entity\Repository\NestedTreeRepository;
use Doctrine\ORM\EntityRepository;
use Kitpages\EdmBundle\Entity\File;
use Kitpages\EdmBundle\EdmException;

/**
 * ItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FileRepository extends EntityRepository
{

    public function getVersionFile($file, $versionNumberToKeep)
    {
        $fileList = $this->_em
            ->createQuery("
                SELECT f
                FROM KitpagesEdmBundle:File f
                LEFT JOIN f.originalVersion ov
                WHERE ov = :fileOriginalVersion
                ORDER BY f.id DESC
              ")
            ->setParameter("fileOriginalVersion", $file->getOriginalVersion())
            ->setMaxResults(1)
            ->setFirstResult($versionNumberToKeep)
            ->getResult();
        if (count($fileList) > 0) {
            return $fileList[0];
        } else {
            throw new EdmException("No version file to delete");
        }
        return $fileList;
    }


}