<?php

namespace Kitpages\EdmBundle\Repository;

use Gedmo\Tree\Entity\Repository\NestedTreeRepository;
use Doctrine\ORM\EntityRepository;

/**
 * ItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NodeRepository extends NestedTreeRepository
{

    /**
     * Get one root node query builder
     *
     * @return Doctrine\ORM\QueryBuilder
     */
    public function getRootNodeByTreeId($treeId)
    {

        return $this->getRootNodesQueryBuilder()
            ->AndWhere(" node.treeId = :treeId")
            ->setParameter("treeId", $treeId);

    }

}