<?php

namespace Kitpages\EdmBundle\Repository;

use Gedmo\Tree\Entity\Repository\NestedTreeRepository;
use Doctrine\ORM\EntityRepository;
use Kitpages\EdmBundle\Entity\Node;
use Kitpages\EdmBundle\EdmException;

/**
 * ItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NodeRepository extends NestedTreeRepository
{

    /**
     * Get one root node query builder
     *
     * @return Doctrine\ORM\QueryBuilder
     */
    public function getRootNodeByTreeId($treeId)
    {

        return $this->getRootNodesQueryBuilder()
            ->AndWhere(" node.treeId = :treeId")
            ->setParameter("treeId", $treeId);

    }

    public function getFirstDirectoryNodeParentByNode($node)
    {
        $node = $this->_em
            ->createQuery("
                SELECT n
                FROM KitpagesEdmBundle:Node n
                WHERE n.right > :right
                  AND n.left < :left
                  AND n.nodeType = :nodeType
                ORDER BY n.left DESC
              ")
            ->setParameter("right", $node->getRight())
            ->setParameter("left", $node->getLeft())
            ->setParameter("nodeType", Node::NODE_TYPE_DIRECTORY)
            ->setMaxResults(1)
            ->getResult();
        if (count($node) > 0) {
            return $node[0];
        } else {
            throw new EdmException("No parent directory");
        }
    }

    public function getNodeByFileId($fileId)
    {
        $node = $this->_em
            ->createQuery("
                SELECT n
                FROM KitpagesEdmBundle:Node n
                INNER JOIN n.file f
                LEFT JOIN f.originalVersion ov
                WHERE f.id = :fileId
                  OR ov.id = :fileId
                ORDER BY f.id DESC
              ")
            ->setParameter("fileId", $fileId)
            ->setMaxResults(1)
            ->getResult();
        if (count($node) > 0) {
            return $node[0];
        } else {
            throw new EdmException("No Node for the file");
        }

    }

}