<?php

namespace Kitpages\EdmBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Kitpages\EdmBundle\Entity\UserPreference;
use Kitpages\EdmBundle\EdmException;

/**
 * ItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserPreferenceRepository extends EntityRepository
{

}